"""initial hypothesis tables

Revision ID: 3c524947e090
Revises: 
Create Date: 2025-11-05 17:08:48.752189

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c524947e090'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hyp_id', sa.String(length=32), nullable=False),
    sa.Column('lab_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_type', sa.String(length=32), nullable=False),
    sa.Column('ai_subtype', sa.String(length=64), nullable=True),
    sa.Column('business_category', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('stage_health', sa.String(length=16), nullable=False),
    sa.Column('stage_history', sa.JSON(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('feasibility_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('risk_class', sa.String(length=16), nullable=False),
    sa.Column('data_requirements', sa.JSON(), nullable=False),
    sa.Column('roi_estimate', sa.JSON(), nullable=True),
    sa.Column('time_estimate', sa.JSON(), nullable=True),
    sa.Column('success_metrics', sa.JSON(), nullable=False),
    sa.Column('gating_checklist', sa.JSON(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('linked_experiments', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('governance_state', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owners', sa.JSON(), nullable=False),
    sa.Column('sponsors', sa.JSON(), nullable=False),
    sa.Column('observers', sa.JSON(), nullable=False),
    sa.Column('activity_digest', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hyp_id')
    )
    op.create_index(op.f('ix_hypotheses_hyp_id'), 'hypotheses', ['hyp_id'], unique=True)
    op.create_table('hypothesis_activity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=160), nullable=False),
    sa.Column('actor_email', sa.String(length=160), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('impact', sa.String(length=16), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_activity_events_hypothesis_id'), 'hypothesis_activity_events', ['hypothesis_id'], unique=False)
    op.create_table('hypothesis_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('approver_name', sa.String(length=160), nullable=False),
    sa.Column('approver_email', sa.String(length=160), nullable=True),
    sa.Column('approver_role', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_approvals_hypothesis_id'), 'hypothesis_approvals', ['hypothesis_id'], unique=False)
    op.create_table('hypothesis_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=160), nullable=True),
    sa.Column('uploaded_by_email', sa.String(length=160), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_attachments_hypothesis_id'), 'hypothesis_attachments', ['hypothesis_id'], unique=False)
    op.create_table('hypothesis_checklist_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=160), nullable=True),
    sa.Column('owner_email', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_checklist_items_hypothesis_id'), 'hypothesis_checklist_items', ['hypothesis_id'], unique=False)
    op.create_table('hypothesis_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('author_name', sa.String(length=160), nullable=False),
    sa.Column('author_email', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['hypothesis_comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_comments_hypothesis_id'), 'hypothesis_comments', ['hypothesis_id'], unique=False)
    op.create_table('hypothesis_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.String(length=32), nullable=True),
    sa.Column('to_stage', sa.String(length=32), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('changed_by', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_stage_history_hypothesis_id'), 'hypothesis_stage_history', ['hypothesis_id'], unique=False)
    op.create_table('hypothesis_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('owner_name', sa.String(length=160), nullable=True),
    sa.Column('owner_email', sa.String(length=160), nullable=True),
    sa.Column('due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('related_stage', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_tasks_hypothesis_id'), 'hypothesis_tasks', ['hypothesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hypothesis_tasks_hypothesis_id'), table_name='hypothesis_tasks')
    op.drop_table('hypothesis_tasks')
    op.drop_index(op.f('ix_hypothesis_stage_history_hypothesis_id'), table_name='hypothesis_stage_history')
    op.drop_table('hypothesis_stage_history')
    op.drop_index(op.f('ix_hypothesis_comments_hypothesis_id'), table_name='hypothesis_comments')
    op.drop_table('hypothesis_comments')
    op.drop_index(op.f('ix_hypothesis_checklist_items_hypothesis_id'), table_name='hypothesis_checklist_items')
    op.drop_table('hypothesis_checklist_items')
    op.drop_index(op.f('ix_hypothesis_attachments_hypothesis_id'), table_name='hypothesis_attachments')
    op.drop_table('hypothesis_attachments')
    op.drop_index(op.f('ix_hypothesis_approvals_hypothesis_id'), table_name='hypothesis_approvals')
    op.drop_table('hypothesis_approvals')
    op.drop_index(op.f('ix_hypothesis_activity_events_hypothesis_id'), table_name='hypothesis_activity_events')
    op.drop_table('hypothesis_activity_events')
    op.drop_index(op.f('ix_hypotheses_hyp_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    # ### end Alembic commands ###
